de.vogella.jsf.todo/src/de/vogella/jsf/todo/model/Todo.java
package de.vogella.jsf.todo.model;

import java.util.Calendar;

public class Todo {
	private String id;
	private String title;
	private String description;
	private int priority;
	private Calendar dueDate;
	
	public Todo(String title, String description, int priority) {
		this.title = title;
		this.description = description;
		this.priority = priority;
	}
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	
	public int getPriority() {
		return priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	} 
	
	public Calendar getDueDate() {
		return dueDate;
	}
	public void setDueDate(Calendar dueDate) {
		this.dueDate = dueDate;
	}

	
	
	
}

de.vogella.jsf.todo/src/de/vogella/jsf/todo/controller/TodoController.java
package de.vogella.jsf.todo.controller;

import java.util.ArrayList;
import java.util.List;

import javax.faces.component.UICommand;
import javax.faces.component.UIForm;
import javax.faces.event.ActionEvent;
import javax.faces.model.SelectItem;

import de.vogella.jsf.todo.model.Todo;

public class TodoController {
	// Domain model related variables
	private List<Todo> todos;
	private Todo todo;

	// JavaServerFaces related variables
	private UIForm form;
	private UIForm tableForm;
	private UICommand addCommand;

	public TodoController() {
		todos = new ArrayList<Todo>();
		todos.add(new Todo("Learn JFS", "Finish this article", 1));
		todos.add(new Todo("Stop drinking to much coffee", "Coffee is evil!", 3));
	}

	public String addNew() {
		todo = new Todo("", "", 3);
		form.setRendered(true);
		addCommand.setRendered(false);
		return null;
	}

	public String save() {
		todos.add(todo);
		form.setRendered(false);
		addCommand.setRendered(true);
		return null;
	}

	public String cancel() {
		todo = null;
		form.setRendered(false);
		addCommand.setRendered(true);
		return null;
	}

	public String delete() {
		todos.remove(todo);
		return null;
	}

	public void displayTable(ActionEvent event) {
		if (event.getComponent().getId().equalsIgnoreCase("hide")) {
			tableForm.setRendered(false);
		} else {
			tableForm.setRendered(true);
		}
	}

	public List<SelectItem> getPriorities() {
		List<SelectItem> list = new ArrayList<SelectItem>();
		list.add(new SelectItem(1, "High"));
		list.add(new SelectItem(2, "Medium"));
		list.add(new SelectItem(3, "Low"));
		return list;
	}

	public List<Todo> getTodos() {
		return todos;
	}

	public void setTodos(List<Todo> todos) {
		this.todos = todos;
	}

	public Todo getTodo() {
		return todo;
	}

	public void setTodo(Todo todo) {
		this.todo = todo;
	}

	public UIForm getForm() {
		return form;
	}

	public void setForm(UIForm form) {
		this.form = form;
	}

	public UICommand getAddCommand() {
		return addCommand;
	}

	public void setAddCommand(UICommand addCommand) {
		this.addCommand = addCommand;
	}

	public UIForm getTableForm() {
		return tableForm;
	}

	public void setTableForm(UIForm tableForm) {
		this.tableForm = tableForm;
	}

}

de.vogella.jsf.todo/WebContent/Todo.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="f" uri="http://java.sun.com/jsf/core"%>
<%@ taglib prefix="h" uri="http://java.sun.com/jsf/html"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>

<LINK href="<%=request.getContextPath()%>/css/mystyle.css"
	rel="stylesheet" type="text/css">
</head>
<body>
<h3>Todo list</h3>
<f:view>
	<h:messages layout="table"></h:messages>

	<%-- Possibility to start a new Todo --%>
	<h:form>
		<h:commandLink binding="#{todoController.addCommand}" accesskey="n"
			action="#{todoController.addNew}" value="Add new Todo">
		</h:commandLink>
	</h:form>


	<h:form binding="#{todoController.form}" rendered="false"
		styleClass="todo">
		<h:panelGrid columns="2">
			<h:outputText value="Title"></h:outputText>
			<h:inputText value="#{todoController.todo.title}" required="true"
				requiredMessage="Title is required">
			</h:inputText>
			<h:outputText value="Description"></h:outputText>
			<h:inputTextarea value="#{todoController.todo.description}" cols="40"
				rows="4"></h:inputTextarea>
			<h:outputText value="Prio"></h:outputText>
			<h:selectOneMenu validatorMessage="required"
				value="#{todoController.todo.priority}">
				<f:selectItems value="#{todoController.priorities}" />
			</h:selectOneMenu>
		</h:panelGrid>
		<h:panelGroup>
			<h:commandButton action="#{todoController.save}" value="Save"
				accesskey="s">
			</h:commandButton>
			<h:commandButton action="#{todoController.cancel}" value="Cancel"
				accesskey="c" immediate="true">
			</h:commandButton>
		</h:panelGroup>
	</h:form>

	<%-- These buttons allow to show and hide the table --%>
	<h:form>
		<h:panelGrid columns="2">
			<h:commandLink id="hide"
				actionListener="#{todoController.displayTable}" value="Hide Table">
			</h:commandLink>
			<h:commandLink id="show"
				actionListener="#{todoController.displayTable}" value="Show Table">
			</h:commandLink>
		</h:panelGrid>
	</h:form>

	<%-- Here we start the form for the data table --%>
	<h:form binding="#{todoController.tableForm}">
		<%-- Here we start the data table --%>

		<h:dataTable value="#{todoController.todos}" var="todo"
			styleClass="todo" headerClass="todoheader"
			columnClasses="first, rest">
			<h:column>
				<%-- Via this facet we define the table header (column 1) --%>
				<f:facet name="header">
					<h:column>
						<h:outputText value="Prio"></h:outputText>
					</h:column>
				</f:facet>
				<h:outputText value="#{todo.priority}"></h:outputText>
			</h:column>
			<h:column>
				<%-- Via this facet we define the table header (column 2) --%>
				<f:facet name="header">
					<h:column>
						<h:outputText value="Title"></h:outputText>
					</h:column>
				</f:facet>
				<h:outputText value="#{todo.title}"></h:outputText>

			</h:column>

			<h:column>
				<%-- Via this facet we define the table header (column 3) --%>
				<f:facet name="header">
					<h:column>
						<h:outputText value="Description"></h:outputText>
					</h:column>
				</f:facet>
				<h:outputText value="#{todo.description}"></h:outputText>
			</h:column>

			<h:column>
				<%-- Via this facet we define the table header (column 4) --%>
				<f:facet name="header">
					<h:column>
						<h:outputText value="Actions"></h:outputText>
					</h:column>
				</f:facet>
				<h:panelGrid columns="2">
					<h:commandLink value="delete" action="#{todoController.delete}">
						<f:setPropertyActionListener target="#{todoController.todo}"
							value="#{todo}" />
					</h:commandLink>
				</h:panelGrid>
			</h:column>
		</h:dataTable>

	</h:form>
</f:view>
</body>
</html>